### ISSUE TITLE
Support of non-square size image

### ISSUE THREAD

**Issue by kelvinkoh0308** [faustomorales/vit-keras#18] opened 2021-04-16 05:25 UTC
Hi,

Currently, the vit-keras only support square size input ( 256x256), could you change it to support non-square size input image like 256 x 128?

Thank you very much.

**Comment by faustomorales** [comment] 2021-04-21 00:19
Supporting non-square input sizes would be non-trivial because it changes how we load pre-trained weights and has ramifications for patch sizes. A PR with support on this would be welcome but I'm afraid I cannot devote time to this in the foreseeable future.

**Comment by Ankit152** [comment] 2021-05-04 15:38
Thank you @faustomorales for such an amazing library. But I would like to ask you how can I train a vision transformer model from your library if I mention `pretrained = False`.  Suppose I want the model to `train on a specific data` not `fine tuning`. I was facing difficulty while doing so. Is there something you can guide me?

**Comment by faustomorales** [comment] 2021-07-06 02:36
Closing since this is not a bug. A PR adding support for non-square images would be welcome.

**Closed by faustomorales** 2021-07-06 02:36 UTC

**Comment by faustomorales** [comment] 2021-07-22 15:33
Non-square functionality added by https://github.com/faustomorales/vit-keras/pull/26.
