### ISSUE TITLE
Multilabel: class-wise attention maps

### ISSUE THREAD

**Issue by rarazac** [faustomorales/vit-keras#23] opened 2021-05-28 14:28 UTC
Do you have any idea if it is possible to generate an attention map per predicted output class?
As an example if there is a dog and a cat in the image I'd like to show the attention given to dog and one given to cat.

**Comment by faustomorales** [comment] 2021-07-06 02:35
I don't know if this is possible with the attention maps in ViT but I recommend looking into model explainers like [Lime](https://github.com/marcotcr/lime) and [SHAP](https://github.com/slundberg/shap). Closing since this is not a bug. Please direct theoretical questions about the architecture to the [official repository](https://github.com/google-research/vision_transformer).

**Closed by faustomorales** 2021-07-06 02:35 UTC

**Comment by rarazac** [comment] 2021-07-06 07:21
Thanks for your response, you are right it is not a bug, Sorry! I also found this one: https://github.com/hila-chefer/Transformer-Explainability may be interesting for you.
