### ISSUE TITLE
load_pretrained - BASE_URL 404 Not Found

### ISSUE THREAD

**Issue by nattafahhm** [faustomorales/vit-keras#28] opened 2021-08-23 04:12 UTC
I want to see models by using load model weights for a known configuration (BASE_URL), as commented.  
But this Page is Not Found https://github.com/faustomorales/vit-keras/releases/download/dl. 

is there any issue?

**Comment by apardogi** [comment] 2021-09-16 08:49
I was able to download all four models today (b16, b32, l16 and l32).

**Comment by StephanElter** [comment] 2022-02-09 18:36
I have similar issue. 
I try to load Model ViT-B_16-224.npz from google cloud by using the URL
[https://github.com/faustomorales/vit-keras/releases/download/dl/ViT-B_16-224_imagenet21k+imagenet2012.npz](https://github.com/faustomorales/vit-keras/releases/download/dl/ViT-B_16-224_imagenet21k+imagenet2012.npz 
but it doesn't work. 
it would be nice if there were also a support for a tiny model  ViT-T_...
regards

**Comment by faustomorales** [comment] 2022-05-03 16:14
Closing because the original issue appeared to be transient, as confirmed by a later comment showing the download worked.

**Closed by faustomorales** 2022-05-03 16:14 UTC
